import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Index.module.css'

import Navigation from "../components/navigation.js"
import Slider from  "../components/slider.js"
import Propos from  "../components/propos.js"
import Prestations from  "../components/prestations.js"
import Contact from  "../components/contact.js"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nathalie Thérapie | Thérapeute en hypnose et soins énergétiques à Annecy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <Slider />

      <Propos />

      <Prestations />

      <Contact />

    </div>
  )
}
