import Head from 'next/head'
import Image from 'next/image'

import Navigation from "../components/navigation/navigation.js"
import Slider from "./sections/slider.js"
import Intro from "./sections/intro.js"
import Propos from "./sections/propos.js"
import Prestations from "./sections/prestations.js"
import Contact from "./sections/contact.js"
import Footer from "../components/footer/footer.js"

export default function Home() {
  return (
    <div className="container">
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-59025910-2"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-59025910-2');
        </script>
      <Head>
        <title>Nathalie Thérapie | Thérapeute en hypnose et soins énergétiques à Annecy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="header">
        <Navigation />
      </div>
      <div className="content">
        <Slider />
        <Intro />
        {/*<Propos />*/}
        <Prestations />
        <Contact />
      </div>
      <Footer />

    </div>
  )
}
